function outHtml = coloredText(inText, inColor)
% return a HTML string with colored font
outHtml = ['<html><font color="', ...
    inColor, ...
    '">', ...
    inText, ...
    '</font></html>'];
end